### ISSUE TITLE
I have 3 error in playlist tab 

### ISSUE THREAD

**Issue by Arundinakaran** [manuarora700/music-streaming-project#4]
![MVIMG_20201215_233725](https://user-images.githubusercontent.com/46997468/102254419-940f2c80-3f2e-11eb-9154-71c5999aa175.jpg)
I have attached a picture
It had few other error and I have solved it 
Please do help me in this 
Thanks in advance @manuarora700

**Comment by manuarora700** [comment]
Check the updated code, I've added the updated db file in repo.
